# Generated by Django 2.1.7 on 2023-09-09 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230909_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 9, 9, 13, 28, 5, 320528)),
        ),
    ]
